      - name: Run enabled checks
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: --config no
      - name: Loop checks
        shell: bash
        run: |
          set -euo pipefail
          checks=(
            EendMissingArgCheck
            EmptyDirsCheck
            EqualVersionsCheck
            FetchablesUrlCheck
            GitCommitMessageCheck
            GitEclassCommitsCheck
            GitPkgCommitsCheck
            GlobCheck
            GlsaCheck
            HomepageCheck
            HomepageUrlCheck
            ImlateCheck
            InheritsCheck
          )
          for check in "${checks[@]}"; do
            echo "==> pkgcheck scan -c $check"
            pkgcheck scan -c "$check"
          done
